name: "setup-ubuntu-latest-xvfb"
description: "Setup xvfb on ubuntu"
runs:
  using: "composite"
  steps:
    - uses: tlambert03/setup-qt-libs@v1
    - name: Enable xvfb on ubuntu
      run: |
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      shell: bash
